name: Monthly Board Game Data Update

on:
  schedule:
    - cron: '0 3 1 * *'
  workflow_dispatch:

permissions:
  contents: write  # ← This is the fix

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - run: pip install -r requirements.txt
      - run: python update_games.py
      - run: cat settings.json
      - uses: EndBug/add-and-commit@v9
        with:
          author_name: GitHub Actions
          author_email: actions@github.com
          message: 'chore: update boardgames and settings.json from GitHub Action'
          add: 'data/boardgames.json data/settings.json'
